name: C#

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        dotnet-version: ['5.0.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Setup IronPython 2.7.11 (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: |
        sudo apt install gnupg ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        sudo apt install mono-devel
        sudo apt install libmono-system-numerics4.0-cil
    - name: Setup IronPython 2.7.11 (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install ironpython
    - name: Setup IronPython 2.7.11 (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install ironpython
    - name: Run tests
      run: |
        dotnet --version
        ipy -V
