name: C#

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        dotnet-version: ['5.0.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Create test directories (POSIX)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        mkdir -p ~/bin ~/logs
    - name: Create test directories (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $dirs = "${env:USERPROFILE}/bin", "${env:USERPROFILE}/logs"
        foreach ($d in $dirs) {
          if (!(test-path $d)) {
            mkdir $d
          }
        }
    - name: Setup IronPython 2.7.11 (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: |
        pwd
        echo ==================
        ls -l
        echo ==================
        wget -q https://github.com/IronLanguages/ironpython2/releases/download/ipy-2.7.11/ironpython_2.7.11.deb -O ironpython_2.7.11.deb
        sudo dpkg -i ironpython_2.7.11.deb
    - name: Setup IronPython 2.7.11 (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        pwd
        echo ==================
        ls -l
        echo ==================
        wget -q https://github.com/IronLanguages/ironpython2/releases/download/ipy-2.7.11/IronPython-2.7.11.pkg -O IronPython-2.7.11.pkg
        sudo installer -pkg IronPython-2.7.11.pkg -target /
    - name: Setup IronPython 2.7.11 (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        choco install --no-progress mono
        choco install --no-progress ironpython --version=2.7.11
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run tests
      run: |
        dotnet --version
        export PATH="/Library/Frameworks/IronPython.framework/Versions/2.7.11/bin:$PATH"
        echo $PATH
        which ipy
        ipy -V
        cd csharp
        cd cs-pythonparser
        dotnet build
        cd ..
        echo "About to run scripts using IronPython"
        ipy -X:FullFrames -X:Debug ptest.py org.parsers.python py
        ipy -X:FullFrames -X:Debug ptest.py --parser ParseModule org.parsers.python py
      env:
        PY_DEBUG: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
