name: Launchers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Build scripts with launchers
      run: |
        mkdir test
        python -c "import sys; print(sys.executable)"
        python -m venv env
        env\bin\pip install distlib==0.3.5
        dir /s env\*.exe
      shell: cmd
      env:
        PY_DEBUG: 1
