name: Tests

on:
  push:
    branches: [ main ]
    paths:
        - '!.github/workflows/*.yml'
        - '.github/workflows/tests.yml'

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['8', '11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - name: Setup Jython 2.7.2 (POSIX)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        wget https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar -O jython.jar
    - name: Setup Jython 2.7.2 (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $source = 'https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar'
        $destination = 'jython.jar'
        Invoke-WebRequest -Uri $source -OutFile $destination
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install PCRE
      if: ${{ matrix.os == 'ubuntu-latest' }}
      #uses: ConorMacBride/install-package@v1
      #with:
        #apt: 'libpcre3-dev'
      run: |
        sudo apt update && sudo apt install libpcre3-dev
    - name: Setup Rust
      uses: moonrepo/setup-rust@v1
      with:
        channel: '1.84.0'
    - name: Run tests
      run: |
        java -jar jython.jar --version
        python --version
        ant -version
        rustc --version
      env:
        PY_DEBUG: 1
